import React from 'react'
import './reset.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
require('dotenv').config()

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: React.PropsWithChildren) => (
    <html lang="en">
        <head>
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
            />
        </head>

        <body>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
    </html>
)

export default RootLayout
